// src/constants/countries.ts
export const ADZUNA_COUNTRIES = [
  { value: "at", label: "Austria" },
  { value: "au", label: "Australia" },
  { value: "be", label: "Belgium" },
  { value: "br", label: "Brazil" },
  { value: "ca", label: "Canada" },
  { value: "ch", label: "Switzerland" },
  { value: "de", label: "Germany" },
  { value: "es", label: "Spain" },
  { value: "fr", label: "France" },
  { value: "gb", label: "United Kingdom" },
  { value: "id", label: "Indonesia" },
  { value: "in", label: "India" },
  { value: "it", label: "Italy" },
  { value: "mx", label: "Mexico" },
  { value: "nl", label: "Netherlands" },
  { value: "nz", label: "New Zealand" },
  { value: "pl", label: "Poland" },
  { value: "ru", label: "Russia" },
  { value: "sg", label: "Singapore" },
  { value: "us", label: "United States" },
  { value: "za", label: "South Africa" },
];
